### ISSUE TITLE
where to get IP and port from?

### ISSUE THREAD

**Issue by venil7** [amorenew/ACS_NFC_Flutter#1]
Hi Thanks for this plugin;

I dont understand
```
    await AcsNfc.openConnection(ip: '192.168.137.1', port: '8001');
```

I connect Acs reader via USB, where am I supposed to get IP and port for it?

**Comment by amreniouinnovent** [comment]
@venil7 Could you put an image of your ACS Reader?

**Comment by amorenew** [comment]
No reply and it is look like a diffrent hardware integration
