### ISSUE TITLE
iOS Support and acr1255u

### ISSUE THREAD

**Issue by EbramTawfik** [amorenew/ACS_NFC_Flutter#5]
I am trying to use the package but I have some question:
1- Does it support iOS?
2- Is there a way to use it with acr1255u? and is there documentation?
https://www.acs.com.hk/en/products/528/acr1255u-j1-acs-secure-bluetooth%C2%AE-nfc-reader-software-development-kit/

**Comment by amorenew** [comment]
Hello,

Actually it is just using TCP connection so it may not fit for your needs

Regards,

**Comment by Mobiwoom** [comment]
I'm also interested in connection with ACR 1255u-J1 device with Bluetooth , any update ?

**Comment by Mobiwoom** [comment]
> I am trying to use the package but I have some question:
> 1- Does it support iOS?
> 2- Is there a way to use it with acr1255u? and is there documentation?
> https://www.acs.com.hk/en/products/528/acr1255u-j1-acs-secure-bluetooth%C2%AE-nfc-reader-software-development-kit/

did you make it work ? regards

**Comment by amorenew** [comment]
@Mobiwoom I don't have the same model but you could use my plugin as a guideline to build based on your own hardware.
